### ISSUE TITLE
Prop Tool 2.5 Debug problem when including OBJ files

### ISSUE THREAD

**Issue by francisbauer** [parallaxinc/Propeller-Tool#119]
While the default collection of Debug examples for PropTool 2.5 work, I have NOT been able to get any Spin2 program to work in Debug mode if the Spin2 file has OBJ files specified.
PropTool keeps complaining about "Debug needing at least 10MHz external/crystal clocking", whenever any OBJ file is included.
Remove the OBJ file(s) and then PropTool will compile successfully.
Turn-off Debug with the OBJ files included and they compile successfully.
It doesn't seem to be related to whether or not any of OBJ files contain any Debug statements or even a CON _clkfreq definition.
All the default Debug examples don't include any OBJ files, so they work fine...
Let me know if you need a simple example.

**Comment by jrullan** [comment]
I too am having this issue, though I did not notice that it was related to objects. I was waiting for this release precisely for the debug function. Here is my screenshot:

![image](https://user-images.githubusercontent.com/6475312/108375086-083ca980-71d8-11eb-9673-ed1eb77fda53.png)

**Comment by PropGit** [comment]
Thanks for reporting this @francisbauer and @jrullan.  I've been working on this today and forgot to report.

For me, it's giving a different error: "Invalid object file: <filename>.obj"

I haven't found what the problem is yet, but I suspect the subobject isn't being stored properly in Propeller Tool when Debug Mode is on.  That's what I'm checking next.

**Comment by PropGit** [comment]
Found the source of the problem; the one that I see directly.  I expect it's causing the problem you reported.  Fixing it will be a little challenging.  I'm targeting a new release tomorrow with this fix.

**Comment by francisbauer** [comment]
> 
> 
> Thanks for reporting this @francisbauer and @jrullan. I've been working on this today and forgot to report.
> 
> For me, it's giving a different error: "Invalid object file: .obj"
> 
> I haven't found what the problem is yet, but I suspect the subobject isn't being stored properly in Propeller Tool when Debug Mode is on. That's what I'm checking next.

I did see the "Invalid object file: .obj" error a couple of times, usually after I tried compiling the 2nd Spin2 file separately and then referencing the Spin2 file later as an OBJ in the primary file.  Where are the intermediate files like *.obj being created during the overall compile process?

**Comment by PropGit** [comment]
> I did see the "Invalid object file: .obj" error a couple of times, usually after I tried compiling the 2nd Spin2 file separately and then referencing the Spin2 file later as an OBJ in the primary file. Where are the intermediate files like *.obj being created during the overall compile process?

Thanks for confirming.  The Propeller Tool is designed to _not_ require files to be saved just to compile (this, to speed up and enhance the development experience, which typically includes lots of iterative trials and experiments before settling on a set of code that "works") so all the intermediate results are generated and held in memory rather than output to storage.  The _exception_ to that is that the user's unsaved code (the code they are actively editing and re-compiling, but haven't manually saved yet) is temporarily saved to storage in the app's temporary data space (assigned by Windows) upon every compilation attempt... this is used as an auto-recovery file should anything bad happen (power failure, fatal serial port hardware access failure, or a bug that maims or kills the app).

The bug causing the issue you found (I think) and certainly the one I see (definitely) seems to be a difference in compilation process between the P1 and P2.  I'm not sure yet, but there may be an attribute of the P1 process that I took advantage of to consolidate code and it appears the difference interjected by the optional debug interpreter (which gets added to the P2 application at the end) is causing the problem; my code is unintentionally adding the debug interpreter at the end of every subobject compilation.  I apparently failed to compile and test any multi-object code with debug mode turned on (though I thought I had), or I'd have run into this error before the first release.

I did a quick test last night to verify my findings and note that the subobjects now are compiled and included properly; however, I need to make an exception for the P2 so that it inserts the debug interpreter at the end (like intended) as a separate step.  My first attempt didn't work because the convenient place (which matches where PNut does it) is too high-level; it doesn't have access to the final in-memory structure(s) at that point.  I'm confident I can make it work right with a little more careful thought and testing this morning.

**Comment by jrullan** [comment]
@PropGit 

Excellent responsiveness from the devs! Thank you for keeping us up to date.

**Comment by PropGit** [comment]
Thanks @jrullan.

I've fixed it and a new release is pending.  It should appear as v2.5.1 on the download page within the next few hours; I'm waiting a little because Chip may have a fix to an issue he found in the debugger and we'd like to include that if possible.
