### ISSUE TITLE
Add Extension To Editor Tabs for Spin Files

### ISSUE THREAD

**Issue by JonMcPhalen** [parallaxinc/Propeller-Tool#37]
For those of us working to port P1 code to the P2, we will often have both file types open at the same time, but get no help from the editor tabs. 

Suggestion: Add .spin or .spin2 extension to the file name in the tab.

This is already done for non-Spin files.

![pt_tabs](https://user-images.githubusercontent.com/4042568/90658081-fd3c9880-e1f7-11ea-9337-29759b1233d5.png)

Another option is to prefix the name (sans extension) with "P1: " or "P2: "

**Comment by PropGit** [comment]
I've been thinking about the same thing, but unsure what would be best.  I'd like something very demur but obvious... an icon would take the same space as an extension (rejected), a color wouldn't be obvious unless learned (rejected).

I prefer your P1: / P2: idea.  Colon's can't be in filenames (on Windows) so that prevents mixups.  I suppose an icon with P1 or P2 would also work there.

**Comment by JonMcPhalen** [comment]
I think you're going with the prefix idea, using "P1: " and "P2: " (note the space after the colon) will be clearer and less work from a coding standpoint, as you don't have to do anything special to add graphics to the tab.

**Comment by PropGit** [comment]
Agreed.

**Comment by PropGit** [comment]
I'm going with the prefix idea for now (maybe permanently).  Will be included in v2.3.0.0 Alpha.

**Comment by PropGit** [comment]
Done.
