### ISSUE TITLE
Registry is showing 2.4.0 folder for 2.5.0 settings

### ISSUE THREAD

**Issue by cjmoorejr** [parallaxinc/Propeller-Tool#99]
![2021-02-17-PropellerRegistryCapture](https://user-images.githubusercontent.com/36820917/108273379-17b8e580-7139-11eb-9083-88b94335c1c1.PNG)

**Comment by PropGit** [comment]
Thanks @cjmoorejr.  I know this seems like a mistake, but it's actually by design.

Later versions of the Propeller Tool (since way back in v1.0 (I think)) use a specific version of its registry settings as long as the newer Propeller Tool version doesn't use any setting in a non-backward compatible way.  This initially was because it was intended that you could run multiple versions of Propeller Tool on the computer at the same time (or one day after another) and if those versions use registry settings in a compatible way, they'd share those settings so that, regardless of what version you start one day or another, you'd have access to the same preferences.

The only time it creates a new group of settings is when any one of them is handled differently (in a backward incompatible way)... that way previous versions (which may be still installed and runnable) continue to work as they were intended, as well as the new version.

In recent versions, they are intended to replace each other, so that's not such an issue, but this feature was maintained in case we need to rely on that old way again.

In truth, normally users don't need to dig into the registry unless there's something wrong that isn't solvable through the Propeller Tool's interface.  Admittedly, the latter is true in a few cases right now while we evolve the software.

**Comment by cjmoorejr** [comment]
That makes sense.  I guessed that might have been the reason I've done
similar things in the past.  Just wanted to mention it in case it was an
oversight.
